### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by bxmas13**

### CODE REVIEW

**Comment by bxmas13** [comment]
Sorry I was in the wrong repo

**Comment by ry167** [comment]
No worries! Please feel free to send a pull request through for any changes you make :smile: donutdan appears to have abandoned his version and I will be maintaining this.
I like the "With additions..." piece, I think I'll add that in here

**Comment by ry167** [comment]
Oh also you are right on `composer require ry167/shopify` not working, I have the `repository` setup in my `composer.json`. I'll update the readme to mention that

**Comment by bxmas13** [comment]
Great! I have a few other changes that you might like. I will create a pull request in the next couple of days.

**Pull request closed without merging**
